"""nuevos settings

Revision ID: 0693855d8e94
Revises: 88dd5ae327fd
Create Date: 2025-09-03 13:13:54.612342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0693855d8e94'
down_revision = '88dd5ae327fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('premios')
    with op.batch_alter_table('estudios', schema=None) as batch_op:
        batch_op.drop_index('idx_estudio_usuario_asignatura')
        batch_op.drop_index('idx_estudio_usuario_id')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trofeo', sa.String(), server_default=sa.text("'Unconditional love &#10084;&#65039;'"), nullable=False))
        batch_op.add_column(sa.Column('extra_time', sa.Integer(), server_default='1800000', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('extra_time')
        batch_op.drop_column('trofeo')

    with op.batch_alter_table('estudios', schema=None) as batch_op:
        batch_op.create_index('idx_estudio_usuario_id', ['usuario_id'], unique=False)
        batch_op.create_index('idx_estudio_usuario_asignatura', ['usuario_id', 'asignatura_id'], unique=False)

    op.create_table('premios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='premios_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='premios_pkey')
    )
    # ### end Alembic commands ###
