"""unique constraint supervisor_estudiante

Revision ID: 1022e83a3c0b
Revises: ce833c542098
Create Date: 2025-07-24 11:03:50.164997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1022e83a3c0b'
down_revision = 'ce833c542098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor_estudiante', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_supervisor_estudiante', ['supervisor_id', 'estudiante_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisor_estudiante', schema=None) as batch_op:
        batch_op.drop_constraint('unique_supervisor_estudiante', type_='unique')

    # ### end Alembic commands ###
