"""mejor nombre a roles

Revision ID: 316608c8e79d
Revises: 6dfa45bb3532
Create Date: 2025-04-08 10:54:03.455398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316608c8e79d'
down_revision = '6dfa45bb3532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(), nullable=True))
        batch_op.drop_column('rol')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('usuarios_rol_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'])
        batch_op.drop_column('rol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('usuarios_rol_fkey', 'roles', ['rol'], ['id'])
        batch_op.drop_column('rol_id')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
