"""study_fun_ratio

Revision ID: 3acde83d79eb
Revises: 0693855d8e94
Create Date: 2025-09-08 12:57:37.471826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3acde83d79eb'
down_revision = '0693855d8e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_ratio', sa.Float(), server_default='1.0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('time_ratio')

    # ### end Alembic commands ###
