"""nuevos modelos para ranking

Revision ID: 3e3bb594326f
Revises: f069f19cc617
Create Date: 2025-02-14 11:36:57.767880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3bb594326f'
down_revision = 'f069f19cc617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niveles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trofeos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tiempos', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['usuario_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiempos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('trofeos')
    op.drop_table('premios')
    op.drop_table('niveles')
    # ### end Alembic commands ###
