"""nueva tabla estado_usuario

Revision ID: 474446b4c5f5
Revises: 337e582a8838
Create Date: 2025-07-18 16:51:29.011648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474446b4c5f5'
down_revision = '337e582a8838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estado_usuario')
    # ### end Alembic commands ###
