"""nullable false

Revision ID: 611d8f9308ff
Revises: 4feda26f13dd
Create Date: 2025-07-26 15:02:17.139976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611d8f9308ff'
down_revision = '4feda26f13dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nuevas_notificaciones', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nuevas_notificaciones', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
