"""cambio tipo de dato registro notas

Revision ID: 66543a7aca70
Revises: be26f0635c70
Create Date: 2025-10-09 18:32:10.967336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66543a7aca70'
down_revision = 'be26f0635c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_notas', schema=None) as batch_op:
        batch_op.alter_column('nota',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_notas', schema=None) as batch_op:
        batch_op.alter_column('nota',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
