"""actividad a tabla de uso

Revision ID: 66b213c545b0
Revises: d1f932bb12d6
Create Date: 2025-03-25 11:23:03.884588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b213c545b0'
down_revision = 'd1f932bb12d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actividad', sa.Text(), nullable=False, server_default=""))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usos', schema=None) as batch_op:
        batch_op.drop_column('actividad')

    # ### end Alembic commands ###
