"""expansion de tabla incentivos

Revision ID: 88dd5ae327fd
Revises: 8a6b2d13f406
Create Date: 2025-08-22 12:48:35.960481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88dd5ae327fd'
down_revision = '8a6b2d13f406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incentivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nota', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incentivos', schema=None) as batch_op:
        batch_op.drop_column('nota')
        batch_op.drop_column('monto')

    # ### end Alembic commands ###
