"""modificacion tabla pais

Revision ID: 8a6b2d13f406
Revises: 52d2f745fa70
Create Date: 2025-08-21 19:18:08.344728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6b2d13f406'
down_revision = '52d2f745fa70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moneda_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'monedas', ['moneda_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pais', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('moneda_id')

    # ### end Alembic commands ###
