"""tabla intermedia supervisor-estudiante

Revision ID: 8f92d8b49e8b
Revises: 316608c8e79d
Create Date: 2025-04-08 14:43:44.037464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f92d8b49e8b'
down_revision = '316608c8e79d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervisor_estudiante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('estudiante_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supervisor_estudiante')
    # ### end Alembic commands ###
