"""notificaciones usuario unique desactivado

Revision ID: 8fda1a7609bb
Revises: 14244ca7bcf4
Create Date: 2025-07-26 22:34:26.929513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fda1a7609bb'
down_revision = '14244ca7bcf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint('notificaciones_usuario_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.create_unique_constraint('notificaciones_usuario_id_key', ['usuario_id'])

    # ### end Alembic commands ###
