"""acumulacion tiempo cantidad a float

Revision ID: b4f8f6bca20d
Revises: deb0f8be82ef
Create Date: 2025-02-14 14:12:55.337317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f8f6bca20d'
down_revision = 'deb0f8be82ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acumulacion_tiempos', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acumulacion_tiempos', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
