"""Add ON DELETE CASCADE to usuario_id FKs

Revision ID: be26f0635c70
Revises: d7c636fd00f3
Create Date: 2025-09-14 12:37:47.194542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be26f0635c70'
down_revision = 'd7c636fd00f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acumulacion_tiempos', schema=None) as batch_op:
        batch_op.drop_constraint('acumulacion_tiempos_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('asignaturas', schema=None) as batch_op:
        batch_op.drop_constraint('asignaturas_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('estado_usuario', schema=None) as batch_op:
        batch_op.drop_constraint('estado_usuario_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('estrellas', schema=None) as batch_op:
        batch_op.drop_constraint('estrellas_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('estudios', schema=None) as batch_op:
        batch_op.drop_constraint('estudio_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('incentivos', schema=None) as batch_op:
        batch_op.drop_constraint('incentivos_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('niveles', schema=None) as batch_op:
        batch_op.drop_constraint('niveles_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint('notificaciones_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('nuevas_notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint('nuevas_notificaciones_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('registro_notas', schema=None) as batch_op:
        batch_op.drop_constraint('registro_notas_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('restricciones', schema=None) as batch_op:
        batch_op.drop_constraint('restricciones_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint('settings_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('solicitud_vinculacion', schema=None) as batch_op:
        batch_op.drop_constraint('solicitud_vinculacion_estudiante_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('solicitud_vinculacion_supervisor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['estudiante_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'usuarios', ['supervisor_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('supervisor_estudiante', schema=None) as batch_op:
        batch_op.drop_constraint('supervisor_estudiante_supervisor_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('supervisor_estudiante_estudiante_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['estudiante_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'usuarios', ['supervisor_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tiempos', schema=None) as batch_op:
        batch_op.drop_constraint('tiempo_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('trofeos', schema=None) as batch_op:
        batch_op.drop_constraint('trofeos_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('usos', schema=None) as batch_op:
        batch_op.drop_constraint('uso_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('uso_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('trofeos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('trofeos_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('tiempos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tiempo_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('supervisor_estudiante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('supervisor_estudiante_estudiante_id_fkey', 'usuarios', ['estudiante_id'], ['id'])
        batch_op.create_foreign_key('supervisor_estudiante_supervisor_id_fkey', 'usuarios', ['supervisor_id'], ['id'])

    with op.batch_alter_table('solicitud_vinculacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('solicitud_vinculacion_supervisor_id_fkey', 'usuarios', ['supervisor_id'], ['id'])
        batch_op.create_foreign_key('solicitud_vinculacion_estudiante_id_fkey', 'usuarios', ['estudiante_id'], ['id'])

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('settings_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('restricciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('restricciones_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('registro_notas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('registro_notas_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('nuevas_notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('nuevas_notificaciones_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notificaciones_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('niveles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('niveles_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('incentivos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('incentivos_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('estudios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('estudio_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('estrellas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('estrellas_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('estado_usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('estado_usuario_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('asignaturas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('asignaturas_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('acumulacion_tiempos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('acumulacion_tiempos_usuario_id_fkey', 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###
