"""estado_usuario usuario_id unique

Revision ID: ce833c542098
Revises: 474446b4c5f5
Create Date: 2025-07-18 16:54:20.715135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce833c542098'
down_revision = '474446b4c5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_usuario', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['usuario_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
