"""remaining_time

Revision ID: d7c636fd00f3
Revises: 3acde83d79eb
Create Date: 2025-09-12 11:19:45.621769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c636fd00f3'
down_revision = '3acde83d79eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usos', schema=None) as batch_op:
        batch_op.drop_column('remaining_time')

    # ### end Alembic commands ###
