"""tipos de datos

Revision ID: e6e1f34a65ab
Revises: b11917e3956d
Create Date: 2025-02-14 13:05:59.845602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e1f34a65ab'
down_revision = 'b11917e3956d'
branch_labels = None
depends_on = None


def upgrade():
    # Convertir 'nivel' en la tabla 'niveles' de VARCHAR a INTEGER
    with op.batch_alter_table('niveles', schema=None) as batch_op:
        batch_op.alter_column(
            'nivel',
            existing_type=sa.VARCHAR(length=100),
            type_=sa.Integer(),
            existing_nullable=True,
            postgresql_using="nivel::integer"
        )

    # Convertir 'cantidad' en la tabla 'trofeos' de VARCHAR a INTEGER
    with op.batch_alter_table('trofeos', schema=None) as batch_op:
        batch_op.alter_column(
            'cantidad',
            existing_type=sa.VARCHAR(length=100),
            type_=sa.Integer(),
            existing_nullable=True,
            postgresql_using="cantidad::integer"
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trofeos', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('niveles', schema=None) as batch_op:
        batch_op.alter_column('nivel',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
